- name: dotfiles dirs
  file:
    path: '~/.{{ item }}'
    state: directory
  loop:
#  - innotop
  - ipython
  - ipython/profile_default
  - ipython/profile_default/startup
  - config
  - config/git

  tags:
  - dotfiles

- name: dotfiles links
  file:
    src: '{{ ansible_env.PWD }}/roles/dan_mac/files/dotfiles/{{ item }}'
    path: '~/.{{ item }}'
    state: link
  loop:
  - ansible.cfg
  - bash_profile
  - config/git/attributes
  - config/git/config
  - config/git/ignore
  - digrc
  - inputrc
  - ssh/config
  - ipython/profile_default/startup/00-imports.py
  - zprofile
  - zshrc
  tags:
  - dotfiles
